# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zara.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QUrl
from PyQt5.QtGui import QIcon, QDesktopServices
from PyQt5.QtWidgets import QApplication, QFrame, QHBoxLayout
from qmaterialwidgets import (NavigationItemPosition, MessageBox, setTheme, Theme, MaterialWindow,
                              SubtitleLabel, setFont)
from qmaterialwidgets import FluentIcon as FIF

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(988, 745)
        self.TonalDropDownPushButton = TonalDropDownPushButton(Dialog)
        self.TonalDropDownPushButton.setGeometry(QtCore.QRect(10, 10, 151, 36))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/feather/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TonalDropDownPushButton.setIcon(icon)
        self.TonalDropDownPushButton.setIconSize(QtCore.QSize(16, 16))
        self.TonalDropDownPushButton.setObjectName("TonalDropDownPushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 200, 171, 171))
        self.label.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/iamges/images/pokemons_studying_for_exam_cute_vibrant_old_anim.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.FilledPushButton = FilledPushButton(Dialog)
        self.FilledPushButton.setGeometry(QtCore.QRect(30, 380, 159, 36))
        self.FilledPushButton.setObjectName("FilledPushButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 200, 171, 171))
        self.label_2.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/iamges/images/pokemon_watching_a_youtube_video_cute_dreamworks.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.FilledPushButton_2 = FilledPushButton(Dialog)
        self.FilledPushButton_2.setGeometry(QtCore.QRect(260, 380, 159, 36))
        self.FilledPushButton_2.setObjectName("FilledPushButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 200, 171, 171))
        self.label_3.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/iamges/images/muscular_man_meditating_in_a_grass_field_illust.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.FilledPushButton_3 = FilledPushButton(Dialog)
        self.FilledPushButton_3.setGeometry(QtCore.QRect(510, 380, 159, 36))
        self.FilledPushButton_3.setObjectName("FilledPushButton_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(750, 200, 171, 171))
        self.label_4.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/iamges/images/handsome_anime_boy_with_glasses_reading_newspape.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.FilledPushButton_4 = FilledPushButton(Dialog)
        self.FilledPushButton_4.setGeometry(QtCore.QRect(710, 380, 251, 36))
        self.FilledPushButton_4.setObjectName("FilledPushButton_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(250, 440, 171, 171))
        self.label_5.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/iamges/images/timetsable.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.FilledPushButton_5 = FilledPushButton(Dialog)
        self.FilledPushButton_5.setGeometry(QtCore.QRect(260, 630, 159, 36))
        self.FilledPushButton_5.setObjectName("FilledPushButton_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 171, 171))
        self.label_6.setStyleSheet("background-image: url(:/images/images/pokemon_watching_a_youtube_video_cute_dreamworks.jpg); border-radius: 55px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/iamges/images/Leonardo_Diffusion_XL_cute_schoolgirl_writing_in_a_note_samdoe_0.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.FilledPushButton_6 = FilledPushButton(Dialog)
        self.FilledPushButton_6.setGeometry(QtCore.QRect(20, 630, 171, 36))
        self.FilledPushButton_6.setObjectName("FilledPushButton_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.TonalDropDownPushButton.setText(_translate("Dialog", "Home"))
        self.FilledPushButton.setText(_translate("Dialog", "Create a todo list"))
        self.FilledPushButton_2.setText(_translate("Dialog", "Save videos locally"))
        self.FilledPushButton_3.setText(_translate("Dialog", "Focus Mode"))
        self.FilledPushButton_4.setText(_translate("Dialog", "Get Summary of a website"))
        self.FilledPushButton_5.setText(_translate("Dialog", "Create a timetable"))
        self.FilledPushButton_6.setText(_translate("Dialog", "Quick sticky notes"))
from qmaterialwidgets import FilledPushButton, TonalDropDownPushButton
import assets


if __name__ == "__main__":
    import sys
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    setTheme(Theme.LIGHT)
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
